name: .NET Core  
  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  
jobs:  
  build:  
  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v2  
    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v1  
      with:  
        dotnet-version: '7.x.x'  
    - name: Install dependencies  
      run: dotnet restore  
    - name: Build  
      run: dotnet build --configuration Release --no-restore  
    - name: Test  
      run: dotnet test --no-restore --verbosity normal  
      
    - name: Retry Publish NuGet
      run: |
          attempt=0
          max_attempts=3
          until [ $attempt -ge $max_attempts ]
          do
            echo "Publishing attempt #$((attempt+1))..."
            npx brandedoutcast/publish-nuget@v2.5.5 \
              PROJECT_FILE_PATH=/home/runner/work/EmailValidator/EmailValidator/ConsoleApplication/ConsoleApplication.csproj \
              PACKAGE_NAME=disposableEmailValidator \
              VERSION_STATIC=1.0.0 \
              NUGET_KEY=${{ secrets.NUGET_API_KEY }} \
              NUGET_SOURCE=https://api.nuget.org/v3/index.json && break
            attempt=$((attempt+1))
            echo "Retrying in 10 seconds..."
            sleep 10
          done 
