name: .NET Core Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - uses: actions/checkout@v2

    # Setup .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x.x'  # Specify .NET version

    # Restore dependencies
    - name: Install dependencies
      run: dotnet restore

    # Clean the build to ensure no old artifacts are present
    - name: Clean build
      run: dotnet clean

    # Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Run tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    # Create the NuGet package
    - name: Pack NuGet package
      run: |
        dotnet pack /home/runner/work/EmailValidator/EmailValidator/ConsoleApplication/ConsoleApplication.csproj \
          --configuration Release \
          --output ./nupkgs

    # Publish NuGet package to NuGet.org
    - name: Publish NuGet package
      run: |
        dotnet nuget push ./nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  # API Key from GitHub Secrets
