name: .NET Core Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - uses: actions/checkout@v2
    
    # Setup .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x.x'  # Specify .NET version

    # Restore dependencies
    - name: Install dependencies
      run: dotnet restore

    # Clean the build to ensure no old artifacts are present
    - name: Clean build
      run: dotnet clean

    # Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Run tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    # Create NuGet package and publish using brandedoutcast/publish-nuget action
    - name: Pack and Publish NuGet package
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        # Path to the .csproj file to pack
        project-path: /home/runner/work/EmailValidator/EmailValidator/ConsoleApplication/ConsoleApplication.csproj
        
        # Output directory for the NuGet package
        output-dir: ./nupkgs

        # The version of the package
        version: 1.0.0

        # Specify the NuGet API key stored in GitHub Secrets
        api-key: ${{ secrets.NUGET_API_KEY }}

        # Optionally, specify the NuGet source (default is NuGet.org)
        nuget-source: https://api.nuget.org/v3/index.json
