name: .NET Core Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - uses: actions/checkout@v2
    
    # Setup .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x.x'  
        
    # Restore dependencies
    - name: Install dependencies
      run: dotnet restore

    # Clean the build to ensure no old artifacts are present
    - name: Clean build
      run: dotnet clean

    # Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Run tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
